name: 'Intervals.icu git backup'
description: 'Automatically backup your Intervals.icu activities a GitHub repository.'
author: 'Anders Ballegaard'
branding:
  icon: 'arrow-up-circle'
  color: 'red'

inputs:
  athlete_id:
    description: 'Intervals.icu Athlete ID'
    required: true
  api_key:
    description: 'Intervals.icu API Key'
    required: true
  output_directory:
    description: 'Directory to store the backup files'
    required: false
    default: 'activities'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run backup script
      shell: bash
      env:
        INTERVALS_ATHLETE_ID: ${{ inputs.athlete_id }}
        INTERVALS_API_KEY: ${{ inputs.api_key }}
        FIT_FILE_BACKUP_DIR: ${{ inputs.output_directory }}
      run: |
        python ${{ github.action_path }}/backup.py

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v1.5.0
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: true
        amend: false
        commit_prefix: "[AUTO]"
        commit_message: "Automatic commit"
        user_name: "Intervals.icu Backup Action"
        user_email: "actions@github.com"
        signing_mode: ""
        signing_key: ""
        signing_passphrase: ""
        force: false
        force_with_lease: false
        no_edit: false
        organization_domain: github.com
        target_branch: update/version
